services:
  - type: web
    name: baseball-pitch-stats
    runtime: python
    plan: professional  # you're already on this
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.enableCORS false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
